name: Tests
on: push
jobs:
  Test:
    name: Test Contracts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('yarn.lock') }}
      - name: install node packages
        if: steps.cache.outputs.cache-hit != 'true'
        id: install_node_packages
        run: yarn
      - name: run tests
        id: run_contract_tests
        run: yarn test